pthread.h

_POSIX_C_SOURCE 200112L {
    PTHREAD_BARRIER_SERIAL_THREAD
    PTHREAD_CANCEL_ASYNCHRONOUS
    PTHREAD_CANCEL_ENABLE
    PTHREAD_CANCEL_DEFERRED
    PTHREAD_CANCEL_DISABLE
    PTHREAD_CANCELED
    PTHREAD_COND_INITIALIZER
    PTHREAD_CREATE_DETACHED
    PTHREAD_CREATE_JOINABLE
    PTHREAD_EXPLICIT_SCHED
    PTHREAD_INHERIT_SCHED
    PTHREAD_MUTEX_INITIALIZER
    PTHREAD_ONCE_INIT
    PTHREAD_PRIO_INHERIT
    PTHREAD_PRIO_NONE
    PTHREAD_PRIO_PROTECT
    PTHREAD_PROCESS_SHARED
    PTHREAD_PROCESS_PRIVATE
    PTHREAD_SCOPE_PROCESS
    PTHREAD_SCOPE_SYSTEM
}

_XOPEN_SOURCE 600 {
    PTHREAD_MUTEX_DEFAULT
    PTHREAD_MUTEX_ERRORCHECK
    PTHREAD_MUTEX_NORMAL
    PTHREAD_MUTEX_RECURSIVE
}
