sys/mman.h

_POSIX_C_SOURCE 200112L {
	PROT_READ
	PROT_WRITE
	PROT_EXEC
	PROT_NONE

	MAP_SHARED
	MAP_PRIVATE
	MAP_FIXED

	# Flags for msync()
	MS_ASYNC
	MS_SYNC
	MS_INVALIDATE

	# For the mlockall() function
	MCL_CURRENT
	MCL_FUTURE

	# To indicate a failure from the mmap() function.
	MAP_FAILED

	POSIX_MADV_NORMAL
	POSIX_MADV_SEQUENTIAL
	POSIX_MADV_RANDOM
	POSIX_MADV_WILLNEED
	POSIX_MADV_DONTNEED

	# Flags for posix_typed_mem_open()
	POSIX_TYPED_MEM_ALLOCATE
	POSIX_TYPED_MEM_ALLOCATE_CONTIG
	POSIX_TYPED_MEM_MAP_ALLOCATABLE
}
